
services:
  api:
    container_name: 'api'
    build: './app/'
    volumes:
      - static:/app/static
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - api_network
    depends_on:
      - postgres
      - nginx

  postgres:
    container_name: 'postgres'
    build: './db/'
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

  nginx:
    container_name: nginx
    build: './nginx/'
    ports:
      - 8080:443
    volumes:
      - static:/lib/share/static/
    networks:
      - api_network
    
volumes:
  postgres_data:
  static:

networks:
  api_network: